### ISSUE TITLE
Support for <table> classifier?

### ISSUE THREAD

**Issue by andrewjamesmott** [javierluraschi/nomnoml#18]
Hi, 

Does this support the table classifier that is available in nomnoml ? 

Thanks

**Comment by andrie** [comment]
@andrewjamesmott, all `nomnoml` syntax should work.  Can you provide a reproducible example that doesn't work, please?

**Comment by andrewjamesmott** [comment]
Hi @andrie ,

Thanks for the response, please see below reprex and output and an image of the expected output generated on https://nomnoml.com/


` library(nomnoml)

nomnoml('[<table>Table Title| Item one | 12 || Item 2 | 15]') `
![image](https://user-images.githubusercontent.com/68604378/101342860-0f137b80-387b-11eb-9dc2-7a695bfc94e5.png)

## expected output:

![image](https://user-images.githubusercontent.com/68604378/101343039-500b9000-387b-11eb-8036-b1d7a59cf462.png)

**Comment by andrie** [comment]
The code for the two examples differ.  In the `nomnoml` version you included the modifier `<table>` and if you include this in the R version you will get the same result:


```r
library(nomnoml)
nomnoml('[<table>Table Title| Item one | 12 || Item 2 | 15]')
```

![image](https://user-images.githubusercontent.com/479998/101344809-f8225880-387d-11eb-8e5f-78ead1ce280a.png)

**Comment by andrewjamesmott** [comment]
sorry, typed that out too quickly, using the `<table>` classifier I get the same result as without.

**Comment by andrewjamesmott** [comment]
Here is the result

``` r
library(nomnoml)
nomnoml('[<table>Table Title| Item one | 12 || Item 2 | 15]')
```

![](https://i.imgur.com/2FBbcev.png)

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by andrie** [comment]
What is the version of the `nomnoml` package that you have installed?  Can you please also try against the current github version?

**Comment by andrewjamesmott** [comment]
I have tried it on 0.2.0 from CRAN and 0.2.1 from github (which I think is the current version?) and get the same result.

**Comment by andrie** [comment]
That's rather strange.  I tried it again, and it still works.  Can you please install the latest version from github, then provide your session info?

```r
sessioninfo::session_info()
```

I'm particularly interested in the commit number of your install of `nomnoml`:

```
 nomnoml     * 0.2.1      2020-12-07 [1] Github (rstudio/nomnoml@b95383b)
```

**Comment by andrewjamesmott** [comment]
```r
- Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/London               
 date     2020-12-08                  

- Packages -------------------------------------------------------------------------------------------------------------
 package     * version date       lib source                          
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)                  
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)                  
 cli           2.2.0   2020-11-20 [1] CRAN (R 4.0.3)                  
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)                  
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.2)                  
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)                  
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)                  
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)                  
 htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)                  
 htmlwidgets   1.5.2   2020-10-03 [1] CRAN (R 4.0.3)                  
 knitr         1.30    2020-09-22 [1] CRAN (R 4.0.3)                  
 nomnoml     * 0.2.1   2020-12-08 [1] Github (rstudio/nomnoml@b95383b)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)                  
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)                  
 processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.3)                  
 ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)                  
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)                  
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)                  
 rlang         0.4.9   2020-11-26 [1] CRAN (R 4.0.3)                  
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.3)                  
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)                  
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)                  
 withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.3)                  
 xfun          0.19    2020-10-30 [1] CRAN (R 4.0.3)                  
```

**Comment by andrewjamesmott** [comment]
I dont know whats changed since yesterday but since downloading the latest version from github it is now working

**Comment by andrie** [comment]
Great!  I made a lot of changes yesterday, including updating the javascript for `nomnoml`.

Thanks for reporting back.
