### ISSUE TITLE
size of UML diagram

### ISSUE THREAD

**Issue by stewartli** [javierluraschi/nomnoml#2]
Thank you very much for this excellent package. 
One question. How can I adjust the size of UML diagram when rendering rmarkdown. I have tried zoom and fontsize, and unable to figure out. Any suggestion, please?

Best regards, 
Stewart Li

**Comment by javierluraschi** [comment]
There are two ways to size `nomnoml`, through `knitr` or exporting as image.

## knitr sizing

Using the standard `knitr` sizing prompts, example follows. I find this quite useful but finicky to get right in some cases, for instance, while working in our book it was hard to output to a custom `ascii` text format, etc. 

````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(nomnoml)
```

```{nomnoml fig.width=10, fig.height=1}
[Hello]
```
````

<img width="961" alt="Screen Shot 2019-06-20 at 5 28 25 PM" src="https://user-images.githubusercontent.com/3478847/59889360-e2b32900-9380-11e9-8f91-82b97a83acd3.png">

## Export as Image

To have full control of how the image is sized, I've been finding myself exporting first as an image and then resizing properly, etc. with code similar to the following:

````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(nomnoml)
```

```{r eval=FALSE}
nomnoml("
[Hello]
", png = "nomnom.png", width = 200, height = 10)
```

![](nomnom.png){width=100px}
````

<img width="968" alt="Screen Shot 2019-06-20 at 5 34 40 PM" src="https://user-images.githubusercontent.com/3478847/59889568-d1b6e780-9381-11e9-9ad1-0c740676595d.png">

**Comment by stewartli** [comment]
Thanks for insightful info. Cheers.
