### ISSUE TITLE
color change not working

### ISSUE THREAD

**Issue by AndrewScribner** [javierluraschi/nomnoml#23]
The following is my souce code, but the .red does not change the fill color, as the documentation says it would. Any ideas?
#.red: fill=red
#spacing: 12
#padding: 4
[JESUS] --- [Andrew Scribner]
[<red> Andrew Scribner] o--- [Council]
[Council] --- [fdsa]

**Comment by aronatkins** [comment]
The `.red` syntax defines a custom classifier style (see https://www.nomnoml.com for additional details the full language definition).

As written, this renders as:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/362187/130146855-840648f2-8fe4-4990-b586-8e6e0faf0f6f.png">

To alter all of the elements, you would use:

```
#fill: red
#spacing: 12
#padding: 4
[JESUS] --- [Andrew Scribner]
[ Andrew Scribner] o--- [Council]
[Council] --- [fdsa]
```

and this version renders as:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/362187/130147053-25831da3-b584-45c1-96a3-93a661f7d18d.png">

The `#.red fill=red` can help if you would like to change the fill for some of the elements, using `<red>`:

```
#.red: fill=red
#spacing: 12
#padding: 4
[JESUS] --- [<red>Andrew Scribner]
[Andrew Scribner] o--- [Council]
[Council] --- [fdsa]
```

<img width="539" alt="image" src="https://user-images.githubusercontent.com/362187/130147217-45619adb-8707-4bbe-8122-67a50109d8dc.png">

To have the same font-weight as the others, you would need:

```
#.red: fill=red bold
```

**Comment by andrie** [comment]
Thanks for answering, @aronatkins.  Your answer seems correct, so I'm closing the issue.
