### ISSUE TITLE
no svg figure displayed in xaringan presentation

### ISSUE THREAD

**Issue by rcst** [javierluraschi/nomnoml#25]
Great package, I love it. 

However, when using the nomnoml knitr engine, the diagram will not be displayed as svg, when I use the option `svg = TRUE`
Example

````
---
title: "Example"
author: "For Instance"
date: '`r format(Sys.Date(), format = "%d. %B %Y")`'
output:
  xaringan::moon_reader:
    lib_dir: lib
    seal: true
    nature:
      ratio: "16:9"
---

```{nomnoml, svg=TRUE}
[Hello]-[World]
```
````
(I save this as index.Rmd)

When I run `xaringan::inf_mr("index.Rmd")`, I see the slide as expected, however, it's not an svg-file, which you can see when I try to save it by right-click &rarr; "Save Image As ...". It gets saved as "canvas.png". Why?
![Bildschirmfoto_2021-10-18_20-45-37](https://user-images.githubusercontent.com/14731447/137789487-6663adc3-2645-4659-90e1-d5df51193810.png)

Changing to `svg=FALSE` seems to have no effect.

**Comment by andrie** [comment]
Yes, that does seem to be the case.

Try using an R chunk instead, since this seems to work correctly:
````
```{r}
nomnoml::nomnoml("[Hello]-[World]", svg = TRUE)
```
````
