### ISSUE TITLE
Errors with webshot, consider switch to webshot2?

### ISSUE THREAD

**Issue by giocomai** [javierluraschi/nomnoml#29]
In order to use `nomnoml` in Rmarkdown documents, the package `webshot` and a local binary of `PhantomJS` are needed. 

I followed relevant instructions, but in spite of some efforts with troubleshooting, I could not get this setup to work, getting errors such as `webshot.js returned failure value: 1`.

The point of this issue, however, is not about troubleshooting `webshot`.

Eventually, I found an easy solution: find and replace all `webshot::` with `webshot2::` in the `nomnoml` package, adjust the function `stop_if_no_phantomjs`, and the messages included in `zzz.R`.... and voilà, everything started to work beautifully. 

As it appears that `webshot2` is ultimately a more modern implementation of `webshot` based on a different and more reliable stack, perhaps switching to `webshot2` would be a net benefit for most users?

I could see also the alternative path of adding a parameter for selecting which tool to use for screenshots, and allow for an easy switch between the two. I'm not sure what would be the best way to name such a parameter, as a user may be confused by the idea that screenshotting is taking place in the background. But ultimately, a "screenshot" parameter, with valid values "webshot" and "webshot2" may still be the most consistent approach, as it would still allow for alternative options if other tools appear down the line. 

Especially if the idea is just to replace `webshot` with `webshot2` the changes are seemingly relatively trivial, even if somewhat opinionated (e.g. would there be a need for something comparable to `stop_if_no_phantomjs`, or would we leave it to `webshot2` to let the user know if something is missing?). Because of such choices, I guess it would be probably easier to deal with this on your side (of course, should you find any merit in this issue), but I remain available for submitting a pull request if you feel this may be useful. Thank you for you attention and for the great tool.

**Comment by andrie** [comment]
Thank you. I'm in the process of switching to `webshot2`.  This was somewhat forced since for reasons I don't understand, `webshot` stopped working under certain conditions when rendering R markdown.

**Comment by andrie** [comment]
Fixed in 76d609d288276c7712f590d7517eb56cdbb72286 (version 0.3.0)

Please let me know if you experience any errors.
