### ISSUE TITLE
svg output ?

### ISSUE THREAD

**Issue by moodymudskipper** [javierluraschi/nomnoml#7]
nomnoml.com proposes svg output, would it be possible to have it available with this package ?

**Comment by javierluraschi** [comment]
Yes, `nomnoml` supports SVG; however, I found it to be a bit buggy compared to PNG, specially sizing text appropriately. It works in 80% of the cases so definitely worth exporting, you can use SVG now with `svg = TRUE`.

**Comment by moodymudskipper** [comment]
amazing thanks!
